[project]
name = "rimtrans"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argparse>=1.4.0",
    "google-genai>=1.24.0",
    "lxml>=6.0.0",
    "pillow>=11.3.0",
    "pydantic>=2.11.7",
    "tqdm>=4.67.1",
]
